apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: nested-nginx
      profile:
        source:
          url: https://github.com/weaveworks/profiles-examples
          tag: nested-nginx/v0.0.1
    - name: nginx-deployment
      kustomize:
        path: nginx/deployment
    - name: nginx-chart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: nginx
        version: "9.3.0"
        defaultValues: |
          service:
            type: ClusterIP
    - name: dependon-chart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: redis
        version: "14.6.1"
        defaultValues: |
          master:
            persistence:
              enabled: false
          replica:
            replicaCount: 0
      dependsOn:
        - name: nginx-deployment
        - name: nginx-chart
